import { StyleSheet } from "react-native";

export const theme = {
  colors: {
    background: "#FAFAF8",
    surface: "#FFFFFF",
    surfaceMuted: "#F5F5F4",
    surfaceSoft: "#E7E5E4",
    border: "#E7E5E4",
    borderMuted: "#D6D3D1",
    text: "#1C1917",
    textMuted: "#78716C",
    textStrong: "#44403C",
    primary: "#3B82F6",
    primaryMuted: "#DBEAFE",
    primarySoft: "#EFF6FF",
    danger: "#EF4444",
    dangerSoft: "#FEF2F2",
    success: "#10B981",
    successSoft: "#ECFDF5",
    warning: "#F59E0B",
    warningSoft: "#FFFBEB",
    info: "#06B6D4",
    infoSoft: "#ECFEFF",
    surfaceOverlay: "#FFFFFFE6",
    textOnDark: "#FFFFFF",
    nebula: "#111111",
  },
  radii: {
    card: 16,
    input: 12,
    pill: 20,
    avatar: 28,
  },
  spacing: {
    xxs: 4,
    xs: 6,
    sm: 8,
    md: 12,
    lg: 14,
    xl: 16,
    xxl: 24,
  },
} as const;

export const buttonPalette = {
  primary: {
    softBackground: "#EFF6FF",
    softText: "#1D4ED8",
    subtleBorder: "#BFDBFE",
    subtleBackground: "#DBEAFE",
    subtleText: "#1D4ED8",
    solidBackground: "#3B82F6",
    solidText: "#FFFFFF",
    line: "#3B82F6",
  },
  info: {
    softBackground: "#ECFEFF",
    softText: "#0E7490",
    subtleBorder: "#A5F3FC",
    subtleBackground: "#CFFAFE",
    subtleText: "#0E7490",
    solidBackground: "#06B6D4",
    solidText: "#FFFFFF",
    line: "#0891B2",
  },
  warning: {
    softBackground: "#FFFBEB",
    softText: "#B45309",
    subtleBorder: "#FDE68A",
    subtleBackground: "#FEF3C7",
    subtleText: "#B45309",
    solidBackground: "#F59E0B",
    solidText: "#FFFFFF",
    line: "#D97706",
  },
  error: {
    softBackground: "#FEF2F2",
    softText: "#DC2626",
    subtleBorder: "#FECACA",
    subtleBackground: "#FEE2E2",
    subtleText: "#DC2626",
    solidBackground: "#EF4444",
    solidText: "#FFFFFF",
    line: "#EF4444",
  },
  success: {
    softBackground: "#ECFDF5",
    softText: "#047857",
    subtleBorder: "#A7F3D0",
    subtleBackground: "#D1FAE5",
    subtleText: "#047857",
    solidBackground: "#10B981",
    solidText: "#FFFFFF",
    line: "#059669",
  },
  neutral: {
    softBackground: "#F5F5F4",
    softText: "#44403C",
    subtleBorder: "#E7E5E4",
    subtleBackground: "#E7E5E4",
    subtleText: "#44403C",
    solidBackground: "#78716C",
    solidText: "#FFFFFF",
    line: "#78716C",
  },
} as const;

export const ui = {
  screen: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    padding: theme.spacing.xl,
    paddingBottom: theme.spacing.xxl,
    gap: theme.spacing.md,
  },
  header: {
    paddingHorizontal: 2,
    marginBottom: 8,
  },
  title: {
    fontSize: 20,
    fontWeight: "600" as const,
    color: theme.colors.text,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    color: theme.colors.textMuted,
  },
  description: {
    color: theme.colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  label: {
    fontSize: 13,
    fontWeight: "600" as const,
    color: theme.colors.text,
  },
  mutedText: {
    color: theme.colors.textMuted,
    fontSize: 13,
  },
  card: {
    borderRadius: theme.radii.card,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  input: {
    minHeight: 46,
    borderRadius: theme.radii.input,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: theme.colors.text,
    backgroundColor: theme.colors.surface,
    fontSize: 15,
  },
  readOnlyInput: {
    justifyContent: "center" as const,
    backgroundColor: theme.colors.surfaceMuted,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: theme.colors.surfaceMuted,
  },
  iconButtonCompact: {
    width: 22,
    height: 22,
    borderRadius: 999,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: theme.colors.surface,
  },
  primaryAvatar: {
    width: 56,
    height: 56,
    borderRadius: theme.radii.avatar,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: theme.colors.text,
  },
  subtleButton: {
    minHeight: 40,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    borderRadius: theme.radii.pill,
    backgroundColor: theme.colors.surfaceSoft,
  },
} as const;
